/* This file is automatically generated from lex.c. DO NOT EDIT. */	
#ifndef LEX_HIDE_H
#define LEX_HIDE_H

T3_CONFIG_LOCAL void _t3_config_restart (FILE *input_file ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config__switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
T3_CONFIG_LOCAL YY_BUFFER_STATE _t3_config__create_buffer (FILE *file,int size ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config__delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config__flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_push_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_pop_buffer_state (yyscan_t yyscanner );
T3_CONFIG_LOCAL YY_BUFFER_STATE _t3_config__scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
T3_CONFIG_LOCAL YY_BUFFER_STATE _t3_config__scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
T3_CONFIG_LOCAL YY_BUFFER_STATE _t3_config__scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void *_t3_config_alloc (yy_size_t ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void *_t3_config_realloc (void *,yy_size_t ,yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_free (void * ,yyscan_t yyscanner );
T3_CONFIG_LOCAL int _t3_config_lex_init (yyscan_t* scanner);
T3_CONFIG_LOCAL int _t3_config_lex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);
T3_CONFIG_LOCAL int _t3_config_lex_destroy (yyscan_t yyscanner );
T3_CONFIG_LOCAL int _t3_config_get_debug (yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_set_debug (int debug_flag ,yyscan_t yyscanner );
T3_CONFIG_LOCAL YY_EXTRA_TYPE _t3_config_get_extra (yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_set_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );
T3_CONFIG_LOCAL FILE *_t3_config_get_in (yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_set_in  (FILE * in_str ,yyscan_t yyscanner );
T3_CONFIG_LOCAL FILE *_t3_config_get_out (yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_set_out  (FILE * out_str ,yyscan_t yyscanner );
T3_CONFIG_LOCAL int _t3_config_get_leng (yyscan_t yyscanner );
T3_CONFIG_LOCAL int _t3_config_get_lineno (yyscan_t yyscanner );
T3_CONFIG_LOCAL void _t3_config_set_lineno (int line_number ,yyscan_t yyscanner );
#endif
